site_name: shiny-forge
theme:
  name: "material"
  features:
    - navigation.instant
    - navigation.instant.prefetch
nav:
  - Home: index.md
  - How To Use: howto.md
  - Supported apps: support.md
  - Reference: 
    - Parsing: reference/parsing.md
    - Building: reference/building.md
    - Config: reference/config.md
    - Hooks: reference/hooks.md
plugins:
- search
- mkdocstrings